Exceptions
----------

for i in range(1, 11):
    print(i)

Exception base class


try:

  error prone code

except:

else:
	
finally:

Beautifulsoup
--------------
https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z crossorigin="anonymous">

libraries
---------
beautifulsoup4
lxml


Logging Module
--------------
debug - 10 - detailed information while diagnosing the problem

info - 20 - note down a confirmation that the code is working as expected

warning  - 30 - just an indication that something unexpected happened

error - 40 - due to some serious problems the software is not execution some functions

critical - to - serious error the program is unable to continue running


Generators, iterators and comprehensions
-----------------------------------------
Generators
----------


Threads
-------
code is executed sequentially or synchronously 


def fun():
    print("hello world")
    print("hello world")
    print("hello world")
    print("hello world")
    print("hello world")


fun()
print("-" * 60)

fun()
print("-" * 60)

fun()
print("-" * 60)


GUI - desktop applications
===========================
Perl, Python, Ruby - TK (tool kit) - is built TCL (tool command language)























\





